name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run Tests
        run: ./gradlew test

      - name: Build all JARs
        run: ./gradlew buildAll

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: |
            message-app/build/libs/*.jar
            message-core/build/libs/*.jar
            message-utils/build/libs/*.jar

      - name: Publish to GitHub Packages
        run: ./gradlew :message-core:publish
        env:
          USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

